/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Common.EventJlistSelected;
import Layout.PanelRight;
import Models.ResponseModel.GetAllMessageResponse;
import Models.ResponseModel.MessItemResponse;
import Utils.Constants;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author Asus
 */
public class App extends javax.swing.JFrame {
    private InetAddress host;
    public static Socket socket;
    public static ObjectOutputStream oos;
    public static ObjectInputStream ois;
    public static String test;
    public static int idUser = -1;
    public PanelRight panelRight= new PanelRight();
    
    /**
     * Creates new form App
     * @param accounts
     */
    public App() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        ImageIcon img = new ImageIcon(getClass().getResource("../Assets/home.jpg"));
        JLabel lb = new JLabel(img, JLabel.CENTER);
        panelContent.add(lb);
        panelLeft2.addEventJListSelected(new EventJlistSelected() {
            @Override
            public void selected(int index) {
                setPanel(panelRight);
                panelRight.updateUsername();
            }
        });
//        connnect();
    }
    
    public void resetPanelLeft(){
        panelLeft2.resetPanelLeft();
    }
    
    public void updateAccountOnlineLeft(ArrayList<String> accOnline){
        panelLeft2.updateAccountOnline(accOnline);
    }
    
    public void updateAccountOnlineRight(ArrayList<String> accOnline){
        panelRight.updateAccountOnline(accOnline);
    }
    
    public void setListMessage(ArrayList<GetAllMessageResponse> messages){
        panelRight.setListMessage(messages);
    }
    
    public void sendNewMessage(GetAllMessageResponse mess){
        panelRight.sendNewMessage(mess);
    }
    
    public void updateStatusMessage(GetAllMessageResponse message){
        panelRight.updateStatusMessage(message);
    }
    
    public void updatePositionItemNewMessage(MessItemResponse mess, String test){
        panelLeft2.updatePositionItemNewMessage(mess, test);
    }
    
    private void connnect() {
        //get the localhost IP address, if server is running on some other IP, you need to use that
        try {
            host = InetAddress.getLocalHost();
                //establish socket connection to server
                socket = new Socket(host.getHostName(), 9876);
                //write to socket using ObjectOutputStream
                oos = new ObjectOutputStream(socket.getOutputStream()); 
                //read to socket using ObjectInputStream
                ois = new ObjectInputStream(socket.getInputStream());
                //BufferedReader is = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                //BufferedWriter os = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
                
                ClientThread clientThread = new ClientThread();
                Thread t = new Thread(clientThread);
                t.start();
                
                Constants.oos = oos;
                Constants.ois = ois;
                Constants.socket = socket;
            
        } catch (IOException ex) {
            try {
                socket.close();
            } catch (IOException ex1) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
//        finally{
//            try{
//                if(socket!=null){
//                    socket.close();
//                }
//            }catch(IOException ex){
//                ex.printStackTrace();
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Components.PanelBorder();
        panelLeft2 = new Layout.PanelLeft();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(panelLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1161, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addComponent(panelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new App().setVisible(true);
//            }
//        });
//    }
    
//    private byte[] fromObjectToByteArray(Object obj){
//        ByteArrayOutputStream bos = new ByteArrayOutputStream();
//        try {
//            ObjectOutputStream oos = new ObjectOutputStream(bos);
//            oos.writeObject(obj);
//            oos.flush();
//            return bos.toByteArray();
//        } catch (IOException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return null;
//    }
//    
//    private Object fromByteArrayToObject(byte[] data){
//        ByteArrayInputStream bis = new ByteArrayInputStream(data);
//        ObjectInputStream is;
//        try {
//            is = new ObjectInputStream(bis);
//            return is.readObject();
//        } catch (Exception ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return null;
//    }
    public void setPanelContent() throws IOException{
        System.out.println("DA VAO");
//        BufferedImage myPicture = ImageIO.read(new File(""));
        ImageIcon img = new ImageIcon(getClass().getResource("../Assets/home.jpg"));
        JLabel lb = new JLabel(img, JLabel.CENTER);
        panelContent.removeAll();
        panelContent.add(lb);
        panelContent.repaint();
        panelContent.revalidate();
    }
    
    private void setPanel(JComponent comp){
        panelContent.removeAll();
        panelContent.add(comp);
        panelContent.repaint();
        panelContent.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.PanelBorder panelBorder1;
    private javax.swing.JPanel panelContent;
    private Layout.PanelLeft panelLeft2;
    // End of variables declaration//GEN-END:variables
}
