/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Models.ResponseModel.GetAllMessageResponse;
import Utils.Constants;

/**
 *
 * @author Asus
 */
public class Conversation extends javax.swing.JPanel {

    /**
     * Creates new form Conversation
     * @param message
     */
    public Conversation(GetAllMessageResponse message) {
        initComponents();
        setOpaque(false);
        if(message.getMessage().getUser_send().equals(Constants.infomation.getId())){
            messageRight2.setText(message.getMessage().getMessage());
            messageLeft2.removeAll();
            messageLeft2.setVisible(false);
            lbStatus.setText(message.getMessage().getStatus());
        }else{
            messageLeft2.setTextMess(message.getMessage().getMessage());
            messageLeft2.setTextName(message.getUsername());
            messageRight2.setVisible(false);
            messageRight2.removeAll();
            lbStatus.setVisible(false);
            lbStatus.removeAll();
        }
        
    }
    
    public void hideNotice(){
        lbNotice.setVisible(false);
        lbNotice.removeAll();
    }
    
    public void openNotice(){
        lbNotice.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageRight2 = new Components.MessageRight();
        lbStatus = new javax.swing.JLabel();
        messageLeft2 = new Components.MessageLeft();
        lbNotice = new javax.swing.JLabel();

        messageRight2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageRight2MouseClicked(evt);
            }
        });

        lbStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStatus.setText("status");

        messageLeft2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageLeft2MouseClicked(evt);
            }
        });

        lbNotice.setBackground(new java.awt.Color(255, 255, 255));
        lbNotice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNotice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotice.setText("Send a message to start a conversation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageRight2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lbNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNotice, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageRight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStatus)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageLeft2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageLeft2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageLeft2MouseClicked
        // TODO add your handling code here:
        System.out.println("START DOWNLOAD...");
    }//GEN-LAST:event_messageLeft2MouseClicked

    private void messageRight2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageRight2MouseClicked
        // TODO add your handling code here:
        System.out.println("START DOWNLOAD...");
    }//GEN-LAST:event_messageRight2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbNotice;
    private javax.swing.JLabel lbStatus;
    private Components.MessageLeft messageLeft2;
    private Components.MessageRight messageRight2;
    // End of variables declaration//GEN-END:variables
}
