/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Layout;

import Common.EventJlistSelected;
import GUI.CreateGroup;
import Models.Account;
import Models.ResponseModel.MessItemResponse;
import Utils.Constants;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author Asus
 */
public class PanelLeft extends javax.swing.JPanel {
    private ArrayList<Account> accounts;
    private EventJlistSelected event;
    
    public void addEventJListSelected(EventJlistSelected event){
        this.event = event;
        listMenu1.addEventJListSelected(event);
    }
    /**
     * Creates new form PanelLeft
     */
    public PanelLeft() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setBackground(new Color(98, 132, 255));
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        if(Constants.messItems != null && !Constants.messItems.isEmpty()){
            init();
        }
    }
    
    public void resetPanelLeft(){
        init();
    }
    
    public void updateAccountOnline(ArrayList<String> accOnline){
        listMenu1.reset();
        for(MessItemResponse item : Constants.messItems){
            listMenu1.addItem(new MessItemResponse(item.getAccountId() ,item.getRoomId(), item.getUsername(), item.getNewMessage(), item.getStatus(), item.getType()));            
        }
        
        listMenu1.repaint();
    }
    
    public void init(){
        txtSearch.setText("");
        listMenu1.reset();
        MessItemResponse messItem = null;
        for(MessItemResponse item : Constants.messItems){
            listMenu1.addItem(new MessItemResponse(item.getAccountId() ,item.getRoomId(), item.getUsername(), item.getNewMessage(), item.getStatus(), item.getType()));            
        }
        
        listMenu1.repaint();
    }
    
    public void updatePositionItemNewMessage(MessItemResponse mess, String test){
        listMenu1.reset();
        
        if(test.equals("TEST1")){
            for(MessItemResponse item : Constants.messItems){
                if(item.getRoomId().equals(mess.getRoomId())){
                    Constants.messItems.remove(item);
                    break;
                }
            }
            
            Constants.messItems.add(0, mess);
        }else if(test.equals("USER_SEND")){
            Constants.messItems.remove(Constants.currentPositionIndex);
            Constants.messItems.add(0, mess);
            Constants.currentPosition = mess;
            Constants.currentPositionIndex = 0;
        }else if(test.equals("USER_RECEIVED_FOCUS")){
            Constants.messItems.remove(Constants.currentPositionIndex);
            Constants.messItems.add(0, mess);
            Constants.currentPosition = mess;
            System.out.println("DA VAO: "+ Constants.currentPosition.getNewMessage());
            Constants.currentPositionIndex = 0;
        }
        
        for(MessItemResponse item : Constants.messItems){
            listMenu1.addItem(new MessItemResponse(item.getAccountId() ,item.getRoomId(), item.getUsername(), item.getNewMessage(), item.getStatus(), item.getType()));        
        }
        
        
        listMenu1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenu1 = new Models.JListModel.JlistMessageItem<>();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(285, 800));

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(285, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZALO fake");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setOpaque(false);

        jScrollPane1.setViewportView(listMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateGroup group = new CreateGroup();
        group.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtSearch.getText().trim().equals("")){
                listMenu1.reset();
                for(MessItemResponse item : Constants.messItems){
                    listMenu1.addItem(new MessItemResponse(item.getAccountId() ,item.getRoomId(), item.getUsername(), item.getNewMessage(), item.getStatus(), item.getType()));        
                }
            }else{
                System.out.println("START SEARCH...");
                listMenu1.reset();
                boolean check = false;
                for(Account acc : Constants.accounts){
                    if(!Constants.infomation.getId().equals(acc.getId()) && acc.getUsername().toUpperCase().contains(txtSearch.getText().trim().toUpperCase())){
                        for(MessItemResponse item : Constants.messItems){
                            if(acc.getId().equals(item.getAccountId())){
                                listMenu1.addItem(new MessItemResponse(item.getAccountId() ,item.getRoomId(), item.getUsername(), "", item.getStatus(), item.getType()));        
                                check = true;
                            }
                        }
                        if(!check){
                            listMenu1.addItem(new MessItemResponse(acc.getId() , "", acc.getUsername(), "", "", "PRIVATE"));
                        }  
                        check = false;
                    }
                }
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gradient = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(gradient);
//        g2.setColor(getBackground());
        g2.fillRect(getWidth() - 15, 0, getWidth(), getHeight());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintChildren(g);
    }
    
    public void initMoving(JFrame frame){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Models.JListModel.JlistMessageItem<String> listMenu1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
