/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Layout;

import Enum.StatusMessage;
import Enum.TypeMessage;
import Models.Message;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.Date;
import java.util.UUID;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;

/**
 *
 * @author Asus
 */
public class PanelRight extends javax.swing.JPanel {

    private final ArrayList<Message> messages = new ArrayList<>();
    /**
     * Creates new form PanelRight
     */
    public PanelRight() {
        initComponents();
        setOpaque(false);
        listMess1.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setBackground(new Color(98, 132, 255));
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        
        
        init();
    }
    
    private void init(){
        messages.add(new Message(UUID.randomUUID(),"Hello khuong", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "1", 2, 1 ));
        messages.add(new Message(UUID.randomUUID(),"Hello kiet", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "2", 1, 2));
        messages.add(new Message(UUID.randomUUID(),"khong co gi", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "3" ,2,1));
        messages.add(new Message(UUID.randomUUID(),"haizzzz", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "4" ,1, 2));
        messages.add(new Message(UUID.randomUUID(),"dang lam gi do", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "5",2,1 ));
        messages.add(new Message(UUID.randomUUID(),"xem hentai", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "6" ,1,2));
        messages.add(new Message(UUID.randomUUID(),"xem chung khong", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "7",1,2 ));
        messages.add(new Message(UUID.randomUUID(),"xem", TypeMessage.TEXT, new Date(), StatusMessage.RECEIVED, "8",2,1 ));
        
        for(Message item : messages){
            listMess1.addItem(item);
        }
        
//        listMess1.indexToLocation(8);
        JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
        vertical.setValue(9);
    }
    
    public void test(Message mess){
        messages.add(mess);
//        for(Message item : messages){
        listMess1.addItem(mess);
//        }
        JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
        vertical.setValue( vertical.getMaximum() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textInput1 = new Components.TextInput();
        jPanel1 = new javax.swing.JPanel();
        imageAvatar1 = new Components.ImageAvatar();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMess1 = new Models.ListMess<>();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 100));

        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icon/8.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(listMess1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(textInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        GradientPaint gradient = new GradientPaint(0, 0, Color.decode("#f2fcfe"), 0, getHeight(), Color.decode("#b2fefa"));
        g2.setPaint(gradient);
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(g); 
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ImageAvatar imageAvatar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Models.ListMess<String> listMess1;
    private Components.TextInput textInput1;
    // End of variables declaration//GEN-END:variables
}
